version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:13-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    #    build: .
    image: ashimbel/elixir:sln
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    # command: ["sh", "-c", "while true; do sleep 2; done"]
    #
    # start interactive: iex -S mix phx.server
    #


  bchaindb:
    image: ashimbel/bigchaindb:all-in-one
    ports:
      - '9984:9984'
      - '9985:9985'
      - '27017:27017'
      - '26657:26657'
    volumes:
      - 'chaindb:/data/db'
      - 'configdb:/data/configdb'
      - 'tendermint:/tendermint'
volumes:
  pgdata:
  chaindb:
  configdb:
  tendermint:

